version: "3"

networks:
  backend:

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 4000:4000
    networks:
    - backend
    env_file:
    - local.env
    volumes:
      - "./src:/app/src:ro"
